### ISSUE TITLE
IME exception on property grid - selecting Cache-item

### ISSUE THREAD

**Issue by MartinFijneman** [STARIONGROUP/COMET-IME-Community-Edition#1283]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

reproducible IME exception when selecting a "cache"-item for a selected parameter. Crash occured on local database, reproducible error on dev-server.

Clicking the first item listed under the "cache" list in the property grid (see screenshot) gives an exception report, with error message details given below.

![image](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/assets/35371313/9c89224a-9c84-405b-a1d3-105440f3825a)

### Steps to Reproduce

* opened engineering model, element definitions browser or product tree
* opened property grid
* selected a parameter
* selected the cache item in the grid, and clicked the first item in the list
this throws the exception report

### Logs

An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DevExpress.Utils.IndexedDictionary`1.get_Indices()
   at DevExpress.Utils.IndexedDictionary`1.IndexOf(T item)
   at DevExpress.Utils.IndexedDictionary`1.System.Collections.Generic.ICollection<T>.Contains(T item)
   at DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.MakeRowVisible(RowHandle handle, Boolean withChildren)
   at DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.OnCurrentRowChanged()
   at DevExpress.Xpf.PropertyGrid.Internal.SelectionStrategy.<>c__DisplayClass16_0.<SelectViaPath>b__0()
   at DevExpress.Xpf.Core.Locker.DoLockedAction(Action action)
   at DevExpress.Xpf.Core.Locker.DoIfNotLocked(Action action)
   at DevExpress.Xpf.PropertyGrid.PropertyGridView.ProcessMouseLeftButtonDown(MouseButtonEventArgs e)
   at DevExpress.Xpf.PropertyGrid.PropertyGridControl.ProcessPreviewMouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at CDP4IME.App.Main()

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
didn't search before posting, this seems reproducible variant of already posted item #1213  although that seemes to describe other situations as well. not sure if this is complete duplicate

**Comment by samatstariongroup** [comment]
remove property grid from installer

**Comment by lxatstariongroup** [comment]
Removed from Installer
